import 'package:flutter_growingio_track/flutter_growingio_track.dart';

name: flutter_growingio_track
description: Flutter Plugin For GrowingIO track 
version: 2.6.0
author: ldk <ldkxingzhe@gmail.com>
homepage: https://www.growingio.com

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_growingio_track:
      git:
        url: https://github.com/growingio/flutter-growingio-track.git

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.growingio.plugin.fluttergrowingiotrack
    pluginClass: FlutterGrowingIOTrackPlugin